resolver: lts-7.9

packages:
    - leap
    - space-age
    - bob
    - run-length-encoding
    - rna-transcription
    - sum-of-multiples
    - difference-of-squares
    - grains
    - hamming
    - nucleotide-count
    - grade-school
    - etl
    - raindrops
    - accumulate
